# Generated by Django 4.1.3 on 2023-04-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactivated'), ('T', 'Terminated')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('year_of_study', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3)),
                ('functional_fees', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('session', models.CharField(blank=True, choices=[('D', 'Day'), ('E', 'Evening'), ('W', 'Weekend')], max_length=3, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(max_length=20)),
                ('telephone_no', models.CharField(max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.course')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('fees_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.feesstructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.student')),
            ],
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=2)),
                ('academic_year', models.CharField(max_length=10)),
                ('is_test_cleared', models.BooleanField(max_length=6, null=True)),
                ('is_exam_cleared', models.BooleanField(max_length=6, null=True)),
                ('is_library_cleared', models.BooleanField(max_length=6, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.student'),
        ),
    ]
