# Generated by Django 4.1.3 on 2023-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('De-activated', 'Deactivated'), ('Terminated', 'Terminated')], max_length=15),
        ),
    ]
