# Generated by Django 4.1.3 on 2023-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='is_library_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Evening', 'Evening'), ('Weekend', 'Weekend')], max_length=8, null=True),
        ),
    ]
