# Generated by Django 4.1.3 on 2023-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0003_alter_clearance_is_library_cleared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='is_exam_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='is_test_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
