# Generated by Django 4.1.3 on 2023-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0004_alter_clearance_is_exam_cleared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1yr'), ('2', '2yr'), ('3', '3yr'), ('4', '4yr')], max_length=3),
        ),
    ]
